import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  mpaySidebar: [{ type: 'autogenerated', dirName: 'mpay' }],
  eftSidebar: [{ type: 'autogenerated', dirName: 'eft' }],
  kuggarSidebar: [{ type: 'autogenerated', dirName: 'kuggar' }],
};

export default sidebars;
